package Forms;

import Forms.CustomPopUp.GlassPanePopup;
import Models.ConexionDB;
import java.awt.Color;
import java.awt.Dimension;

import javax.swing.JFrame;

import Values.Colores;
import static Values.Imagenes.getScaledImage;
import java.awt.BorderLayout;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Leoni
 */
public class MainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */

    private ConfigDBPP diagDB = new ConfigDBPP(this);

    public MainAdmin() {
        initComponents();
        GlassPanePopup.install(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Dimension size = getSize();
        bg.setSize(size.width, size.height);
        btnConfigDB.setBorder(Colores.borderxl);
        btnPedidos.setBorder(Colores.borderxl);

        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/Media/LogoCyH_mini.png")); // Cambia la ruta por la ubicación de tu logo

        int width = 300; // Cambia el ancho deseado
        int height = 300; // Cambia el alto deseado

        Image scaledImg = getScaledImage(logoIcon.getImage(), width, height);

        // Crear un nuevo ImageIcon con la imagen escalada
        ImageIcon scaledIcon = new ImageIcon(scaledImg);

        // Crear una etiqueta para mostrar el logo
        JLabel logoLabel = new JLabel(scaledIcon);
        logoLabel.setBackground(Color.WHITE);
        pnlLogo.add(logoLabel, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        plLogin = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        btnConfigDB = new javax.swing.JPanel();
        btnConfig = new javax.swing.JLabel();
        btnPedidos = new javax.swing.JPanel();
        jLabelx6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                bgresize(evt);
            }
        });

        plLogin.setBackground(Colores.cFondoMenu);
        plLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        plLogin.setName(""); // NOI18N

        pnlLogo.setBackground(Colores.cFondoMenu);
        pnlLogo.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout plLoginLayout = new javax.swing.GroupLayout(plLogin);
        plLogin.setLayout(plLoginLayout);
        plLoginLayout.setHorizontalGroup(
            plLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        plLoginLayout.setVerticalGroup(
            plLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLoginLayout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfigDB.setBackground(Colores.cbtnMActions);
        btnConfigDB.setBorder(Colores.borderxl);
        btnConfigDB.setForeground(new java.awt.Color(0, 0, 0));
        btnConfigDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigDB.setMaximumSize(new java.awt.Dimension(300, 300));
        btnConfigDB.setPreferredSize(new java.awt.Dimension(400, 300));
        btnConfigDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigDBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfigDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfigDBMouseExited(evt);
            }
        });

        btnConfig.setBackground(java.awt.Color.darkGray);
        btnConfig.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        btnConfig.setForeground(new java.awt.Color(255, 255, 255));
        btnConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfig.setText("CONFIGURAR DB");
        btnConfig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnConfigDBLayout = new javax.swing.GroupLayout(btnConfigDB);
        btnConfigDB.setLayout(btnConfigDBLayout);
        btnConfigDBLayout.setHorizontalGroup(
            btnConfigDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnConfigDBLayout.setVerticalGroup(
            btnConfigDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfigDBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPedidos.setBackground(Colores.cbtnMActions);
        btnPedidos.setForeground(new java.awt.Color(0, 0, 0));
        btnPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedidos.setMaximumSize(new java.awt.Dimension(300, 300));
        btnPedidos.setPreferredSize(new java.awt.Dimension(400, 300));
        btnPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPedidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPedidosMouseExited(evt);
            }
        });

        jLabelx6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelx6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jLabelx6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelx6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx6.setText("PROBAR CONEXION");
        jLabelx6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnPedidosLayout = new javax.swing.GroupLayout(btnPedidos);
        btnPedidos.setLayout(btnPedidosLayout);
        btnPedidosLayout.setHorizontalGroup(
            btnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelx6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnPedidosLayout.setVerticalGroup(
            btnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelx6, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ADMINISTRACION");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(plLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(btnConfigDB, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(139, 139, 139)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfigDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgresize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bgresize
        Dimension size = getSize();
        bg.setSize(size.width, size.height);
    }//GEN-LAST:event_bgresize

    private void btnConfigDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigDBMouseClicked
        GlassPanePopup.showPopup(diagDB);

    }//GEN-LAST:event_btnConfigDBMouseClicked

    private void btnConfigDBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigDBMouseEntered
        btnConfigDB.setBackground(Colores.cbtnMEnt);
    }//GEN-LAST:event_btnConfigDBMouseEntered

    private void btnConfigDBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigDBMouseExited
        btnConfigDB.setBackground(Colores.cbtnMActions);
    }//GEN-LAST:event_btnConfigDBMouseExited

    private void btnPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMouseClicked
        ConexionDB verify = new ConexionDB();
        Connection con = verify.getConnection();

        LoginPP obj = new LoginPP();
        if (con != null) {
            obj.setText("La conexion a la base de datos esta funcionando correctamente!!");
            obj.setTitle("Informacion");
            GlassPanePopup.showPopup(obj);
        } else {
            obj.setText("No hay conexion a la base de datos, verifique las credenciales eh intentelo de nuevo!!");
            obj.setTitle("Advertencia");
            GlassPanePopup.showPopup(obj);
        }


    }//GEN-LAST:event_btnPedidosMouseClicked

    public void reiniciarAplicacion() {
        GlassPanePopup.closePopupLast();

        AdminClose obj = new AdminClose(this);
        obj.setText("Los campos se han actualizado correctamente, de clic en 'Aceptar' para cerrar el programa y aplicar los cambios o hagalo manualmente!!");
        obj.setTitle("Advertencia");
        GlassPanePopup.showPopup(obj);

//         
    }

    public void cerrarAplicacion() {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

//         Cerrar la aplicación actual
        System.exit(0);
    }

    private void btnPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMouseEntered
        btnPedidos.setBackground(Colores.cbtnMEnt);
    }//GEN-LAST:event_btnPedidosMouseEntered

    private void btnPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMouseExited
        btnPedidos.setBackground(Colores.cbtnMActions);
    }//GEN-LAST:event_btnPedidosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnConfig;
    private javax.swing.JPanel btnConfigDB;
    private javax.swing.JPanel btnPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelx6;
    private javax.swing.JPanel plLogin;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
